<?php

namespace ContainerJB9e4Cw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7gda5CXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7gda5CX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7gda5CX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'prodottiRepository' => ['privates', 'App\\Repository\\ProdottiRepository', 'getProdottiRepositoryService', true],
            'prodottiService' => ['privates', 'App\\Services\\ProdottiService', 'getProdottiServiceService', true],
        ], [
            'prodottiRepository' => 'App\\Repository\\ProdottiRepository',
            'prodottiService' => 'App\\Services\\ProdottiService',
        ]);
    }
}
