<?php

namespace ContainerJB9e4Cw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProdottiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\ProdottiService' shared autowired service.
     *
     * @return \App\Services\ProdottiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'ProdottiService.php';

        return $container->privates['App\\Services\\ProdottiService'] = new \App\Services\ProdottiService(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
    }
}
