controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_reviva_products_list:
    path: /catalogo
    controller: App\Controller\ProductListController::getProductsList