controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_reviva_catalogo:
    path: /catalogo
    controller: App\Controller\CatalogoController::getCatalogo
    
app_reviva_cart:
    path: /cart
    controller: App\Controller\CartController::getCart