<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCHVwLRx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCHVwLRx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCHVwLRx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCHVwLRx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCHVwLRx\App_KernelDevDebugContainer([
    'container.build_hash' => 'CHVwLRx',
    'container.build_id' => '93ffa9a9',
    'container.build_time' => 1641433697,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCHVwLRx');
